name: Build and upload Go binaries

on:
  push:
    paths:
      -  '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  release-binaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Release linux/amd64 
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.23
          binary_name: vxinstagram-linux-amd64
          build_flags: 'ldflags "-s -w" -tags=jsoniter'

      - name: Release linux/arm64
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: arm64
          goversion: 1.23
          binary_name: vxinstagram-linux-arm64
          build_flags: 'ldflags "-s -w" -tags=jsoniter'

      - name: Release windows/amd64
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: amd64
          goversion: 1.23
          binary_name: "vxinstagram-windows-amd64.exe"
          build_flags: 'ldflags "-s -w" -tags=jsoniter'
