name: Build and upload Go binaries

on:
  push:
    paths:
      -  '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64"]
        exclude:
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
          - uses: actions/checkout@v4
          - uses: wangyoucao577/go-release-action@v1
            with:
              github_token: ${{ secrets.TOKEN }}
              goos: ${{ matrix.goos }}
              goarch: ${{ matrix.goarch }}
