name: Build and upload Go binaries

on:
  push:
    paths:
      -  '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    name: Build Go project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Binary linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -tags=jsoniter -o vxinstagram-linux-amd64 .

      - name: Build Binary darwin/amd64
        run: GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -tags=jsoniter -o vxinstagram-darwin-amd64 .

      - name: Upload Binary Artifact linux/amd64
        uses: actions/upload-artifact@v4
        with:
          name: vxinstagram-linux-amd64
          path: vxinstagram-linux-amd64

      - name: Upload Binary Artifact darwin/amd64
        uses: actions/upload-artifact@v4
        with:
          name: vxinstagram-darwin-amd64
          path: vxinstagram-darwin-amd64

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download linux/am64
        uses: actions/download-artifact@v4
        with:
          name: vxinstagram-linux-amd64
          path: .

      - name: Download darwin/amd64
        uses: actions/download-artifact@v4
        with:
          name: vxinstagram-darwin-amd64
          path: .

      - name: Get Commit Message
        id: commit_message
        run: echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body: "${{ env.MESSAGE }}"
          files: |
            vxinstagram-linux-amd64
            vxinstagram-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}