name: Build and upload Go binaries

on:
  push:
    paths:
      -  '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    name: Build Go project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Binary linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -tags=jsoniter -o vxinstagram-linux-amd64 .

      - name: Build Binary darwin/amd64
        run: GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -tags=jsoniter -o vxinstagram-darwin-amd64 .

      - name: Build Binary windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -tags=jsoniter -o vxinstagram-windows-amd64.exe

      - name: Upload Binary Artifact linux/amd64
        uses: actions/upload-artifact@v4
        with:
          name: vxinstagram-linux-amd64
          path: vxinstagram-linux-amd64

      - name: Upload Binary Artifact darwin/amd64
        uses: actions/upload-artifact@v4
        with:
          name: vxinstagram-darwin-amd64
          path: vxinstagram-darwin-amd64

      - name: Upload Binary Artifact for Windows AMD64
        uses: actions/upload-artifact@v4
        with:
          name: "vxinstagram-windows-amd64.exe"
          path: "vxinstagram-windows-amd64.exe"

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download linux/ad64
        uses: actions/download-artifact@v4
        with:
          name: vxinstagram-linux-amd64
          path: .

      - name: Download darwin/amd64
        uses: actions/download-artifact@v4
        with:
          name: vxinstagram-darwin-amd64
          path: .

      - name: Download windows/amd64 (yucky)
        uses: actions/download-artifact@v4
        with:
          name: "vxinstagram-windows-arm64.exe"
          path: .
